/* ==========================================================================
   YOUTUBE BUSINESS 360° — prompts-data.js
   Les 150 prompts IA de la formation, extraits du livre "YouTube Business
   360°" (Partie 16), organisés en 16 catégories. Consommé par prompts.js.
   ========================================================================== */

const PROMPTS_DATA = [
  {
    "id": 1,
    "category": "NICHE",
    "title": "Générateur de sous-niches",
    "objective": "obtenir des sous-niches précises à partir d'un sujet large.",
    "when": "en tout début de projet (Partie 02).",
    "prompt": "Propose-moi 10 sous-niches précises dans le domaine [MON SUJET], chacune avec un public cible différent et une frustration précise à laquelle elle répond.",
    "variables": "[MON SUJET]",
    "example": "[MON SUJET] = \"fitness\" génère des sous-niches comme \"fitness à domicile pour hommes 30-45 ans débutants\".",
    "result": "une liste de 10 sous-niches exploitables pour l'Exercice 1 (Partie 02)."
  },
  {
    "id": 2,
    "category": "NICHE",
    "title": "Évaluateur de niche",
    "objective": "obtenir une première estimation de la viabilité d'une niche.",
    "when": "après avoir présélectionné une niche.",
    "prompt": "Évalue la niche suivante selon ces critères : demande, concurrence, potentiel de revenus, facilité de production. Niche : [MA NICHE]. Donne une note sur 10 pour chaque critère et justifie brièvement.",
    "variables": "[MA NICHE]",
    "example": "[MA NICHE] = \"maquillage 5 minutes pour femmes actives\".",
    "result": "une évaluation à croiser avec ta propre grille de notation (Partie 02, Exercice 2)."
  },
  {
    "id": 3,
    "category": "NICHE",
    "title": "Détection de frustrations",
    "objective": "identifier les frustrations réelles d'une audience cible.",
    "when": "pour affiner le positionnement.",
    "prompt": "Liste 10 frustrations fréquentes que rencontre [MON AUDIENCE] en lien avec [MON SUJET], formulées comme elles le diraient elles-mêmes.",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "[MON AUDIENCE] = \"salariés qui veulent entreprendre\", [MON SUJET] = \"entrepreneuriat\".",
    "result": "une base de sujets de vidéos directement liés à de vraies frustrations."
  },
  {
    "id": 4,
    "category": "NICHE",
    "title": "Comparateur de sous-niches",
    "objective": "comparer plusieurs sous-niches pressenties.",
    "when": "en phase de décision finale de niche.",
    "prompt": "Compare ces sous-niches : [LISTE DE SOUS-NICHES]. Pour chacune, indique le niveau de concurrence estimé et le potentiel de différenciation.",
    "variables": "[LISTE DE SOUS-NICHES]",
    "example": "comparer \"fitness à domicile hommes 30-45\" vs \"fitness postnatal pour jeunes mamans\".",
    "result": "une aide à la décision, à confirmer avec une vraie observation de concurrents (Partie 03)."
  },
  {
    "id": 5,
    "category": "NICHE",
    "title": "Test du nom de niche",
    "objective": "vérifier si une sous-niche est formulée de façon assez précise.",
    "when": "juste avant de valider son positionnement.",
    "prompt": "Voici ma sous-niche : [MA NICHE]. Est-elle assez précise pour cibler un public identifiable ? Si non, propose une version plus précise.",
    "variables": "[MA NICHE]",
    "example": "[MA NICHE] = \"cuisine\" suggestion : \"recettes 15 minutes pour étudiants qui ne savent pas cuisiner\".",
    "result": "une validation ou un affinage de la sous-niche choisie."
  },
  {
    "id": 6,
    "category": "NICHE",
    "title": "Angles de niche originaux",
    "objective": "sortir des angles trop évidents sur une niche connue.",
    "when": "quand la niche choisie semble déjà très occupée.",
    "prompt": "Pour la niche [MA NICHE], propose 5 angles peu exploités par les créateurs existants.",
    "variables": "[MA NICHE]",
    "example": "[MA NICHE] = \"développement personnel\" angle \"développement personnel pour introvertis au travail\".",
    "result": "des pistes de différenciation à croiser avec l'analyse concurrentielle (Partie 03)."
  },
  {
    "id": 7,
    "category": "NICHE",
    "title": "Vérification de la monétisation potentielle",
    "objective": "anticiper les modèles de monétisation adaptés à une niche.",
    "when": "avant de s'engager durablement dans une niche.",
    "prompt": "Pour la niche [MA NICHE], quels modèles de monétisation (parmi publicité, affiliation, coaching, formation, ebook, e-commerce, services, sponsoring, génération de prospects) sont les plus adaptés, et pourquoi ?",
    "variables": "[MA NICHE]",
    "example": "[MA NICHE] = \"coaching sportif à domicile\" coaching et affiliation matériel ressortent naturellement.",
    "result": "une première orientation à approfondir en Partie 12."
  },
  {
    "id": 8,
    "category": "NICHE",
    "title": "Test de durabilité",
    "objective": "vérifier qu'une niche reste intéressante à produire sur la durée.",
    "when": "en cas de doute sur sa motivation à long terme.",
    "prompt": "Si je publie 2 vidéos par semaine sur [MA NICHE] pendant 1 an, quels types de sujets risquent de s'épuiser, et lesquels ont un potentiel de renouvellement ?",
    "variables": "[MA NICHE]",
    "example": "[MA NICHE] = \"critique de restaurants dans une seule ville\".",
    "result": "une anticipation des limites de contenu à long terme."
  },
  {
    "id": 9,
    "category": "NICHE",
    "title": "Positionnement en une phrase",
    "objective": "formuler un positionnement clair.",
    "when": "à la fin du travail sur la niche.",
    "prompt": "Rédige 5 versions d'une phrase de positionnement pour une chaîne sur [MA NICHE], qui s'adresse à [MON AUDIENCE], sur le modèle : \"Ma chaîne aide [avatar] à [résultat], contrairement à [alternative], parce que [différenciateur].\"",
    "variables": "[MA NICHE], [MON AUDIENCE]",
    "example": "niche beauté, audience femmes actives pressées.",
    "result": "des variantes à comparer pour l'Exercice 4 (Partie 02)."
  },
  {
    "id": 10,
    "category": "NICHE",
    "title": "Noms de chaîne cohérents avec la niche",
    "objective": "générer des idées de noms de chaîne.",
    "when": "après validation du positionnement.",
    "prompt": "Propose 10 noms de chaîne courts et mémorables pour une chaîne sur [MA NICHE], positionnée comme [MON POSITIONNEMENT].",
    "variables": "[MA NICHE], [MON POSITIONNEMENT]",
    "example": "niche \"voyage petit budget\", positionnement \"voyager en Europe pour moins de 30€/jour\".",
    "result": "une base de noms à tester pour la Partie 04."
  },
  {
    "id": 11,
    "category": "AUDIENCE",
    "title": "Portrait d'avatar détaillé",
    "objective": "construire un avatar précis.",
    "when": "Partie 02, Exercice 3.",
    "prompt": "Construis un avatar détaillé pour l'audience de ma chaîne sur [MA NICHE] : âge, situation de vie, frustration principale, ce qu'il a déjà essayé, ce qu'il recherche vraiment.",
    "variables": "[MA NICHE]",
    "example": "niche \"entrepreneuriat pour salariés\".",
    "result": "une base à affiner avec de vraies observations (commentaires, échanges directs)."
  },
  {
    "id": 12,
    "category": "AUDIENCE",
    "title": "Questions fréquentes de l'audience",
    "objective": "lister les questions que se pose réellement l'audience.",
    "when": "pour préparer des idées de contenu.",
    "prompt": "Liste 15 questions que se pose [MON AUDIENCE] à propos de [MON SUJET], formulées comme elles les taperaient dans une barre de recherche.",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "audience \"débutants en musculation\", sujet \"prise de muscle\".",
    "result": "une base d'idées de vidéos et de mots-clés SEO (Partie 09)."
  },
  {
    "id": 13,
    "category": "AUDIENCE",
    "title": "Langage de l'audience",
    "objective": "identifier le vocabulaire réellement utilisé par l'audience.",
    "when": "pour écrire des titres et scripts qui sonnent naturels.",
    "prompt": "Quel vocabulaire, expressions ou tournures utilise typiquement [MON AUDIENCE] pour parler de [MON SUJET] ? Liste 10 expressions.",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "audience \"étudiants\", sujet \"gestion du stress avant les examens\".",
    "result": "un vocabulaire à réinjecter dans les titres (Partie 05) et scripts (Partie 06)."
  },
  {
    "id": 14,
    "category": "AUDIENCE",
    "title": "Segmentation d'audience",
    "objective": "identifier plusieurs segments au sein d'une audience large.",
    "when": "si la niche semble encore trop générale.",
    "prompt": "Au sein de l'audience [MON AUDIENCE], identifie 3 segments différents avec des besoins distincts.",
    "variables": "[MON AUDIENCE]",
    "example": "audience \"personnes intéressées par la cuisine\" segments étudiants, parents pressés, passionnés.",
    "result": "une aide à choisir un segment prioritaire plutôt qu'un public trop large."
  },
  {
    "id": 15,
    "category": "AUDIENCE",
    "title": "Objections de l'audience",
    "objective": "anticiper les freins d'achat ou d'engagement de l'audience.",
    "when": "avant de proposer une offre payante (Partie 12).",
    "prompt": "Quelles sont les objections probables de [MON AUDIENCE] face à une offre de [TYPE D'OFFRE] sur le sujet [MON SUJET] ?",
    "variables": "[MON AUDIENCE], [TYPE D'OFFRE], [MON SUJET]",
    "example": "audience \"débutants\", offre \"formation payante\", sujet \"montage vidéo\".",
    "result": "des objections à anticiper dans le contenu ou le tunnel de vente."
  },
  {
    "id": 16,
    "category": "AUDIENCE",
    "title": "Journée type de l'avatar",
    "objective": "mieux comprendre le contexte de vie de l'audience.",
    "when": "pour affiner le ton et les horaires de publication.",
    "prompt": "Décris une journée type de [MON AVATAR], en particulier les moments où il pourrait regarder des vidéos YouTube sur [MON SUJET].",
    "variables": "[MON AVATAR], [MON SUJET]",
    "example": "avatar \"jeune parent actif\", sujet \"recettes rapides\".",
    "result": "des indices sur le ton, le format et le moment de publication adaptés."
  },
  {
    "id": 17,
    "category": "AUDIENCE",
    "title": "Comparaison avec l'audience d'un concurrent",
    "objective": "différencier son audience de celle d'un concurrent proche.",
    "when": "en complément de l'analyse concurrentielle (Partie 03).",
    "prompt": "En quoi l'audience visée par une chaîne sur [MA NICHE] avec le positionnement [MON POSITIONNEMENT] pourrait différer de l'audience typique d'une chaîne généraliste sur le même sujet ?",
    "variables": "[MA NICHE], [MON POSITIONNEMENT]",
    "example": "positionnement \"voyage petit budget\" vs chaînes voyage généralistes.",
    "result": "une clarification du public réellement visé."
  },
  {
    "id": 18,
    "category": "AUDIENCE",
    "title": "Niveau de connaissance de l'audience",
    "objective": "calibrer le niveau de vulgarisation nécessaire.",
    "when": "avant d'écrire un script technique.",
    "prompt": "Quel est le niveau de connaissance probable de [MON AUDIENCE] sur [MON SUJET] ? Quels termes techniques faudra-t-il expliquer au premier usage ?",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "audience \"débutants complets\", sujet \"SEO YouTube\".",
    "result": "une liste de termes à définir simplement dans le script (voir la règle du livre en Partie 0, section niveau du lecteur)."
  },
  {
    "id": 19,
    "category": "AUDIENCE",
    "title": "Évolution de l'audience dans le temps",
    "objective": "anticiper comment l'audience peut évoluer avec la chaîne.",
    "when": "pour planifier une stratégie de contenu à moyen terme.",
    "prompt": "Si mon audience actuelle est [MON AUDIENCE], comment pourrait-elle évoluer après 6 mois à suivre du contenu sur [MA NICHE] ? Quels nouveaux besoins pourraient apparaître ?",
    "variables": "[MON AUDIENCE], [MA NICHE]",
    "example": "audience \"débutants en entrepreneuriat\" après 6 mois de contenu régulier.",
    "result": "des idées de contenu \"niveau intermédiaire\" à prévoir dans le calendrier (Partie 10)."
  },
  {
    "id": 20,
    "category": "AUDIENCE",
    "title": "Message de bienvenue pour nouveaux abonnés",
    "objective": "rédiger un message d'accueil cohérent avec l'avatar.",
    "when": "pour la description de chaîne ou un email de bienvenue (Partie 12, Modèle 9).",
    "prompt": "Rédige un court message de bienvenue pour un nouvel abonné de ma chaîne sur [MA NICHE], qui s'adresse directement à [MON AVATAR].",
    "variables": "[MA NICHE], [MON AVATAR]",
    "example": "niche \"éducation\", avatar \"élève en difficulté en mathématiques\".",
    "result": "un message d'accueil aligné avec le ton défini en Partie 04."
  },
  {
    "id": 21,
    "category": "IDÉES DE VIDÉOS",
    "title": "20 idées à partir d'une niche",
    "objective": "générer rapidement une liste d'idées de vidéos.",
    "when": "Partie 05, Exercice 6.",
    "prompt": "Génère 20 idées de vidéos pour une chaîne sur [MA NICHE], s'adressant à [MON AUDIENCE], réparties entre questions fréquentes, comparaisons, erreurs communes et frustrations.",
    "variables": "[MA NICHE], [MON AUDIENCE]",
    "example": "niche \"fitness à domicile\", audience \"hommes débutants 30-45 ans\".",
    "result": "une base de départ pour ton calendrier (Partie 10)."
  },
  {
    "id": 22,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées à partir des commentaires",
    "objective": "transformer des commentaires en idées de vidéos.",
    "when": "quand tu as déjà une chaîne active.",
    "prompt": "Voici une liste de commentaires reçus sur mes vidéos : [COLLER LES COMMENTAIRES]. Identifie 10 idées de vidéos à partir des questions ou frustrations exprimées.",
    "variables": "[COLLER LES COMMENTAIRES]",
    "example": "commentaires demandant des précisions sur un point mal expliqué.",
    "result": "des idées directement validées par une vraie demande."
  },
  {
    "id": 23,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées de type comparaison",
    "objective": "générer des idées sous forme de comparaison.",
    "when": "pour varier les formats de contenu.",
    "prompt": "Propose 10 idées de vidéos de type \"X vs Y\" pertinentes pour la niche [MA NICHE].",
    "variables": "[MA NICHE]",
    "example": "niche \"outils de montage vidéo\".",
    "result": "des idées à fort potentiel de clic (curiosité de comparaison)."
  },
  {
    "id": 24,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées à partir d'erreurs fréquentes",
    "objective": "générer des idées basées sur des erreurs communes.",
    "when": "pour un contenu à forte valeur perçue.",
    "prompt": "Liste 10 erreurs fréquentes commises par les débutants dans [MA NICHE], formulées comme des idées de titres de vidéos.",
    "variables": "[MA NICHE]",
    "example": "niche \"photographie pour débutants\".",
    "result": "des idées de vidéos avec un fort potentiel de CTR (Partie 05)."
  },
  {
    "id": 25,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées à partir d'une actualité",
    "objective": "relier une actualité récente à sa niche.",
    "when": "pour profiter d'un pic d'intérêt temporaire.",
    "prompt": "Voici une actualité récente : [DESCRIPTION DE L'ACTUALITÉ]. Comment pourrais-je la relier à ma niche [MA NICHE] dans une vidéo pertinente et non superficielle ?",
    "variables": "[DESCRIPTION DE L'ACTUALITÉ], [MA NICHE]",
    "example": "nouvelle fonctionnalité YouTube annoncée, niche \"conseils YouTube\".",
    "result": "une idée de vidéo d'actualité alignée avec le positionnement."
  },
  {
    "id": 26,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées \"débutant complet\"",
    "objective": "couvrir les bases pour les tout premiers spectateurs.",
    "when": "en début de chaîne, pour construire une base solide de contenu.",
    "prompt": "Propose 10 idées de vidéos essentielles pour un débutant complet en [MA NICHE], qui n'a jamais été exposé au sujet.",
    "variables": "[MA NICHE]",
    "example": "niche \"investissement\".",
    "result": "une série de fondations qui pourra devenir une playlist \"Débuter\" (Partie 04)."
  },
  {
    "id": 27,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées orientées résultats",
    "objective": "générer des idées formulées autour d'un résultat concret.",
    "when": "pour des titres à fort bénéfice perçu.",
    "prompt": "Propose 10 idées de vidéos formulées autour d'un résultat concret et mesurable pour l'audience de [MA NICHE].",
    "variables": "[MA NICHE]",
    "example": "niche \"productivité\" \"Comment gagner 1h par jour sans changer ton emploi du temps\".",
    "result": "des idées avec une promesse claire, utile pour la Partie 05."
  },
  {
    "id": 28,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées de série ou format récurrent",
    "objective": "imaginer un format récurrent facilitant la régularité.",
    "when": "pour simplifier le calendrier de contenu (Partie 10).",
    "prompt": "Propose 5 formats de série récurrente adaptés à la niche [MA NICHE], publiables chaque semaine avec un minimum de préparation.",
    "variables": "[MA NICHE]",
    "example": "niche \"cuisine rapide\" série hebdomadaire \"1 recette, 3 ingrédients\".",
    "result": "un format qui facilite la production continue."
  },
  {
    "id": 29,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées liées à la monétisation",
    "objective": "générer des idées qui préparent naturellement une offre payante.",
    "when": "en lien avec la Partie 12.",
    "prompt": "Propose 10 idées de vidéos gratuites qui pourraient naturellement amener vers une offre de [TYPE D'OFFRE] sur le sujet [MON SUJET].",
    "variables": "[TYPE D'OFFRE], [MON SUJET]",
    "example": "offre \"formation\", sujet \"montage vidéo\".",
    "result": "des idées alignées avec un futur tunnel de conversion."
  },
  {
    "id": 30,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées pour public débutant vs avancé",
    "objective": "distinguer les idées selon le niveau de l'audience.",
    "when": "quand l'audience commence à se diversifier.",
    "prompt": "Pour la niche [MA NICHE], propose 5 idées de vidéos pour un public débutant et 5 idées pour un public plus avancé.",
    "variables": "[MA NICHE]",
    "example": "niche \"photographie\".",
    "result": "une base pour organiser des playlists par niveau (Partie 04)."
  },
  {
    "id": 31,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées à partir d'un objectif business",
    "objective": "générer des idées alignées avec un objectif précis (ex. vendre un service).",
    "when": "pour du contenu orienté conversion.",
    "prompt": "Je veux atteindre l'objectif suivant : [MON OBJECTIF]. Propose 10 idées de vidéos qui m'aident à m'en rapprocher, sans sonner promotionnel.",
    "variables": "[MON OBJECTIF]",
    "example": "objectif \"attirer des clients en coaching sportif\" (voir cas David).",
    "result": "des idées cohérentes avec le Modèle 3 (Partie 12)."
  },
  {
    "id": 32,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées de format Shorts",
    "objective": "décliner des idées de vidéos longues en format court.",
    "when": "pour alimenter les Shorts en parallèle du contenu long.",
    "prompt": "À partir de cette idée de vidéo longue : [IDÉE], propose 5 déclinaisons possibles en format Shorts.",
    "variables": "[IDÉE]",
    "example": "idée longue \"10 erreurs en musculation\" Shorts sur chaque erreur individuellement.",
    "result": "un contenu Shorts cohérent avec le contenu long (voir Catégorie 8)."
  },
  {
    "id": 33,
    "category": "IDÉES DE VIDÉOS",
    "title": "Idées à partir d'un cas pratique réel",
    "objective": "transformer une expérience personnelle en contenu.",
    "when": "pour un contenu authentique et différenciant.",
    "prompt": "Voici une expérience personnelle : [DESCRIPTION DE L'EXPÉRIENCE]. Comment la transformer en une idée de vidéo utile pour [MON AUDIENCE] ?",
    "variables": "[DESCRIPTION DE L'EXPÉRIENCE], [MON AUDIENCE]",
    "example": "échec de lancement de chaîne (voir cas \"échec et rebond\", Partie 14).",
    "result": "une idée de vidéo authentique et différenciante."
  },
  {
    "id": 34,
    "category": "IDÉES DE VIDÉOS",
    "title": "Vérification de pertinence d'une idée",
    "objective": "valider qu'une idée correspond bien au positionnement.",
    "when": "avant de scripter une vidéo.",
    "prompt": "Voici mon positionnement : [MON POSITIONNEMENT]. Cette idée de vidéo est-elle cohérente avec ce positionnement : [IDÉE DE VIDÉO] ? Si non, comment l'ajuster ?",
    "variables": "[MON POSITIONNEMENT], [IDÉE DE VIDÉO]",
    "example": "positionnement \"voyage petit budget\", idée \"hôtel 5 étoiles à Dubaï\".",
    "result": "une vérification rapide de cohérence éditoriale (voir Partie 15, règle de cohérence)."
  },
  {
    "id": 35,
    "category": "IDÉES DE VIDÉOS",
    "title": "Banque d'idées mensuelle",
    "objective": "générer un stock d'idées pour tout un mois d'un coup.",
    "when": "lors de la préparation du calendrier de contenu (Partie 10).",
    "prompt": "Génère 4 idées de vidéos pour chaque semaine du mois prochain, sur la niche [MA NICHE], en variant les formats (question, comparaison, erreur, résultat).",
    "variables": "[MA NICHE]",
    "example": "niche \"éducation financière\".",
    "result": "un stock d'idées directement transférable dans le tableau de calendrier (Partie 10, Exercice 12)."
  },
  {
    "id": 36,
    "category": "TITRES",
    "title": "10 variantes de titre",
    "objective": "générer plusieurs formulations d'un même titre.",
    "when": "Partie 05, Exercice 7.",
    "prompt": "Voici une idée de vidéo : [IDÉE]. Propose 10 titres différents, combinant curiosité, spécificité et bénéfice, sans exagérer par rapport au contenu réel.",
    "variables": "[IDÉE]",
    "example": "idée \"comment créer sa chaîne YouTube\".",
    "result": "une liste de titres à comparer et affiner."
  },
  {
    "id": 37,
    "category": "TITRES",
    "title": "Titre à partir d'un chiffre",
    "objective": "intégrer un chiffre précis pour renforcer la spécificité.",
    "when": "quand le contenu contient un résultat mesurable.",
    "prompt": "Reformule ce titre en y intégrant un chiffre précis et crédible : [TITRE].",
    "variables": "[TITRE]",
    "example": "\"Comment perdre du ventre\" \"Comment perdre 3 cm de tour de taille en 14 jours\".",
    "result": "un titre plus concret et engageant."
  },
  {
    "id": 38,
    "category": "TITRES",
    "title": "Titre orienté question",
    "objective": "transformer une affirmation en question intrigante.",
    "when": "pour renforcer la curiosité.",
    "prompt": "Transforme ce titre affirmatif en titre sous forme de question intrigante, sans perdre en clarté : [TITRE].",
    "variables": "[TITRE]",
    "example": "\"5 erreurs en photographie\" \"Pourquoi tes photos ne sont jamais nettes ?\"",
    "result": "une variante à tester en A/B si la plateforme le permet."
  },
  {
    "id": 39,
    "category": "TITRES",
    "title": "Titre orienté erreur",
    "objective": "construire un titre autour d'une erreur fréquente.",
    "when": "pour un contenu de type \"erreurs à éviter\".",
    "prompt": "Écris 5 titres construits autour d'une erreur fréquente commise par [MON AUDIENCE] à propos de [MON SUJET].",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "audience \"débutants en cuisine\", sujet \"cuisson des pâtes\".",
    "result": "des titres à fort potentiel de CTR (voir Partie 05)."
  },
  {
    "id": 40,
    "category": "TITRES",
    "title": "Titre avant/après",
    "objective": "construire un titre basé sur une transformation.",
    "when": "pour du contenu de type transformation ou résultat.",
    "prompt": "Écris 5 titres de type \"avant/après\" pour une vidéo sur [MON SUJET], destinée à [MON AUDIENCE].",
    "variables": "[MON SUJET], [MON AUDIENCE]",
    "example": "sujet \"rangement de bureau\", audience \"freelances\".",
    "result": "des titres qui suggèrent un résultat visible."
  },
  {
    "id": 41,
    "category": "TITRES",
    "title": "Vérification d'exagération",
    "objective": "s'assurer qu'un titre reste honnête par rapport au contenu.",
    "when": "avant publication, en vérification finale.",
    "prompt": "Voici mon titre : [TITRE] et un résumé de ma vidéo : [RÉSUMÉ]. Ce titre promet-il plus que ce que la vidéo livre réellement ?",
    "variables": "[TITRE], [RÉSUMÉ]",
    "example": "titre \"Deviens riche en 1 mois\", contenu réaliste sur l'épargne.",
    "result": "une alerte si le titre risque de nuire à la rétention (Partie 01)."
  },
  {
    "id": 42,
    "category": "TITRES",
    "title": "Titre court pour Shorts",
    "objective": "adapter un titre au format court.",
    "when": "pour la Catégorie 8 (Shorts).",
    "prompt": "Raccourcis ce titre pour un format Shorts, en gardant l'essentiel de la promesse : [TITRE LONG].",
    "variables": "[TITRE LONG]",
    "example": "titre long détaillé version courte percutante.",
    "result": "un titre adapté au format vertical et rapide."
  },
  {
    "id": 43,
    "category": "TITRES",
    "title": "Titre avec mot-clé SEO",
    "objective": "intégrer un mot-clé recherché dans un titre accrocheur.",
    "when": "en lien avec la Partie 09.",
    "prompt": "Intègre le mot-clé [MOT-CLÉ] de façon naturelle dans un titre accrocheur pour une vidéo sur [MON SUJET].",
    "variables": "[MOT-CLÉ], [MON SUJET]",
    "example": "mot-clé \"comment créer une chaîne YouTube\", sujet identique.",
    "result": "un titre qui reste à la fois attractif et bien référencé."
  },
  {
    "id": 44,
    "category": "TITRES",
    "title": "Titre pour public débutant",
    "objective": "adapter un titre à un public qui ne connaît pas encore le sujet.",
    "when": "pour du contenu d'introduction.",
    "prompt": "Reformule ce titre pour qu'il soit compréhensible par un débutant complet, sans jargon : [TITRE].",
    "variables": "[TITRE]",
    "example": "titre trop technique version accessible.",
    "result": "un titre aligné avec le niveau du lecteur visé (voir règles du livre)."
  },
  {
    "id": 45,
    "category": "TITRES",
    "title": "Titre orienté bénéfice temporel",
    "objective": "insister sur la rapidité d'un résultat.",
    "when": "pour du contenu promettant un gain de temps.",
    "prompt": "Réécris ce titre en insistant sur la rapidité du résultat obtenu : [TITRE].",
    "variables": "[TITRE]",
    "example": "\"Comment créer une chaîne YouTube\" \"Crée ta chaîne YouTube en 30 minutes\".",
    "result": "un titre à bénéfice temporel clair (voir exemple Partie 05)."
  },
  {
    "id": 46,
    "category": "TITRES",
    "title": "5 titres pour une même vidéo à tester",
    "objective": "préparer un test A/B de titre.",
    "when": "sur une vidéo à fort potentiel.",
    "prompt": "Propose 5 titres très différents pour la même vidéo sur [MON SUJET], afin de les tester successivement.",
    "variables": "[MON SUJET]",
    "example": "sujet \"erreurs en musculation\".",
    "result": "plusieurs options à tester selon les outils disponibles sur la plateforme."
  },
  {
    "id": 47,
    "category": "TITRES",
    "title": "Titre inspiré d'une frustration précise",
    "objective": "ancrer le titre dans une frustration réelle de l'audience.",
    "when": "en lien avec le Prompt N°03 (Catégorie 1).",
    "prompt": "À partir de cette frustration : [FRUSTRATION], propose 5 titres de vidéo qui y répondent directement.",
    "variables": "[FRUSTRATION]",
    "example": "frustration \"je n'ai jamais le temps de cuisiner sainement\".",
    "result": "des titres directement connectés à une vraie douleur de l'audience."
  },
  {
    "id": 48,
    "category": "TITRES",
    "title": "Titre avec curiosité négative",
    "objective": "utiliser la curiosité liée à un risque ou une erreur.",
    "when": "pour un contenu correctif ou préventif.",
    "prompt": "Propose 5 titres qui utilisent la curiosité liée à un risque ou une erreur à éviter, sur le sujet [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet \"investissement débutant\".",
    "result": "des titres à fort potentiel de clic, sans tomber dans l'alarmisme excessif."
  },
  {
    "id": 49,
    "category": "TITRES",
    "title": "Titre cohérent avec la miniature",
    "objective": "vérifier la cohérence entre titre et concept de miniature.",
    "when": "juste avant la production de la miniature (Partie 07).",
    "prompt": "Voici mon titre : [TITRE]. Propose 3 concepts de miniature qui le complètent sans le répéter mot pour mot.",
    "variables": "[TITRE]",
    "example": "titre \"Pourquoi tes vidéos n'ont aucune vue\".",
    "result": "des pistes visuelles à transmettre pour la Catégorie 11 (Miniatures)."
  },
  {
    "id": 50,
    "category": "TITRES",
    "title": "Reformulation après mauvais CTR",
    "objective": "retravailler un titre existant qui sous-performe.",
    "when": "en lien avec le diagnostic Analytics (Partie 11).",
    "prompt": "Cette vidéo a un CTR faible malgré de bonnes impressions. Voici son titre actuel : [TITRE ACTUEL] et son contenu : [RÉSUMÉ]. Propose 5 nouveaux titres.",
    "variables": "[TITRE ACTUEL], [RÉSUMÉ]",
    "example": "cas 1 de la Partie 11 (bonnes impressions, CTR faible, bonne rétention).",
    "result": "des titres alternatifs à tester pour corriger spécifiquement le CTR."
  },
  {
    "id": 51,
    "category": "HOOKS",
    "title": "Hook à partir d'un titre",
    "objective": "générer un hook cohérent avec un titre donné.",
    "when": "Partie 05, Exercice 8.",
    "prompt": "Voici mon titre : [TITRE]. Écris 3 hooks de moins de 10 secondes qui reprennent directement sa promesse.",
    "variables": "[TITRE]",
    "example": "titre \"3 erreurs qui ruinent tes séances de sport à la maison\" (cas David).",
    "result": "des hooks prêts à tester à l'oral pour vérifier leur rythme."
  },
  {
    "id": 52,
    "category": "HOOKS",
    "title": "Hook basé sur une tension",
    "objective": "créer une tension immédiate en ouverture.",
    "when": "pour renforcer la rétention des premières secondes.",
    "prompt": "Écris un hook qui crée une tension autour de l'idée suivante : [IDÉE PRINCIPALE], sans révéler la réponse complète.",
    "variables": "[IDÉE PRINCIPALE]",
    "example": "idée \"la plupart des gens se trompent sur la cause principale de fatigue\".",
    "result": "un hook qui donne envie de connaître la suite (voir Partie 06)."
  },
  {
    "id": 53,
    "category": "HOOKS",
    "title": "Hook basé sur un résultat visuel",
    "objective": "annoncer un aperçu du résultat final.",
    "when": "pour du contenu avec un résultat visuel fort (avant/après).",
    "prompt": "Écris un hook qui annonce un aperçu du résultat final pour une vidéo sur [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet \"transformation d'un bureau en désordre\".",
    "result": "un hook qui suscite l'envie de voir la suite visuellement."
  },
  {
    "id": 54,
    "category": "HOOKS",
    "title": "Hook qui interpelle directement",
    "objective": "s'adresser directement au spectateur dès la première phrase.",
    "when": "pour renforcer l'identification immédiate.",
    "prompt": "Écris un hook qui interpelle directement [MON AUDIENCE] à propos de [FRUSTRATION].",
    "variables": "[MON AUDIENCE], [FRUSTRATION]",
    "example": "audience \"créateurs débutants\", frustration \"vidéos sans vues\".",
    "result": "un hook à la deuxième personne, immédiatement identifiable."
  },
  {
    "id": 55,
    "category": "HOOKS",
    "title": "Hook avec chiffre choc",
    "objective": "utiliser un chiffre marquant en ouverture.",
    "when": "quand une statistique appuie le sujet.",
    "prompt": "Intègre ce chiffre de façon percutante dans un hook : [CHIFFRE/STATISTIQUE], pour une vidéo sur [MON SUJET].",
    "variables": "[CHIFFRE/STATISTIQUE], [MON SUJET]",
    "example": "statistique liée à un taux d'échec ou de réussite dans la niche.",
    "result": "un hook renforcé par une donnée concrète et vérifiée."
  },
  {
    "id": 56,
    "category": "HOOKS",
    "title": "Hook qui casse une idée reçue",
    "objective": "ouvrir sur une remise en question d'une croyance commune.",
    "when": "pour un contenu qui corrige une erreur répandue.",
    "prompt": "Écris un hook qui remet en question l'idée reçue suivante : [IDÉE REÇUE], liée au sujet [MON SUJET].",
    "variables": "[IDÉE REÇUE], [MON SUJET]",
    "example": "idée reçue \"il faut un gros budget pour voyager\" (cas voyage petit budget, Partie 14).",
    "result": "un hook qui capte l'attention par contraste avec une croyance connue."
  },
  {
    "id": 57,
    "category": "HOOKS",
    "title": "Hook très court pour Shorts",
    "objective": "condenser un hook au format ultra-court.",
    "when": "pour la Catégorie 8 (Shorts), où les 1-2 premières secondes sont décisives.",
    "prompt": "Condense ce hook en une phrase de moins de 5 secondes à l'oral, pour un format Shorts : [HOOK LONG].",
    "variables": "[HOOK LONG]",
    "example": "hook complet réduit à l'essentiel.",
    "result": "un hook adapté à l'exigence extrême de rapidité des Shorts."
  },
  {
    "id": 58,
    "category": "HOOKS",
    "title": "Hook basé sur une erreur personnelle",
    "objective": "ouvrir sur une anecdote personnelle qui capte l'attention.",
    "when": "pour renforcer l'authenticité et la confiance.",
    "prompt": "Écris un hook basé sur une erreur personnelle liée à [MON SUJET], sans être trop long.",
    "variables": "[MON SUJET]",
    "example": "sujet \"lancement de chaîne YouTube\" (voir cas \"échec et rebond\", Partie 14).",
    "result": "un hook qui crée une connexion immédiate par l'authenticité."
  },
  {
    "id": 59,
    "category": "HOOKS",
    "title": "Vérification de longueur et rythme du hook",
    "objective": "s'assurer qu'un hook reste dans le temps imparti.",
    "when": "juste avant le tournage.",
    "prompt": "Voici mon hook : [HOOK]. Est-il lisible à voix haute en moins de 10 secondes ? Si non, raccourcis-le.",
    "variables": "[HOOK]",
    "example": "hook trop long avec plusieurs idées mélangées.",
    "result": "un hook resserré et efficace à l'oral."
  },
  {
    "id": 60,
    "category": "HOOKS",
    "title": "5 variantes de hook pour une même vidéo",
    "objective": "préparer plusieurs options de hook à tester.",
    "when": "sur une vidéo stratégique.",
    "prompt": "Propose 5 variantes de hook pour une vidéo sur [MON SUJET], en utilisant des approches différentes (tension, chiffre, interpellation, idée reçue, anecdote).",
    "variables": "[MON SUJET]",
    "example": "sujet \"comment gagner ses premiers 1000 abonnés\" (voir Partie 07).",
    "result": "plusieurs options à tester à l'oral avant de choisir la version finale."
  },
  {
    "id": 61,
    "category": "SCRIPTS",
    "title": "Script complet en 9 blocs",
    "objective": "générer un premier jet de script complet.",
    "when": "Partie 06, Exercice 9.",
    "prompt": "Rédige un script complet en 9 blocs (Hook, Promesse, Introduction, Développement, Exemple, Pattern interrupt, Transition, Conclusion, CTA) pour une vidéo sur [MON SUJET], destinée à [MON AUDIENCE].",
    "variables": "[MON SUJET], [MON AUDIENCE]",
    "example": "sujet \"créer sa première chaîne YouTube en 2026\" (voir exemple complet Partie 06).",
    "result": "une base de script à retravailler dans ton propre ton."
  },
  {
    "id": 62,
    "category": "SCRIPTS",
    "title": "Développement structuré en étapes",
    "objective": "structurer clairement le bloc \"développement\" d'un script.",
    "when": "pour un contenu de type tutoriel.",
    "prompt": "Découpe le sujet [MON SUJET] en étapes claires et numérotées, adaptées à un script vidéo pour [MON AUDIENCE].",
    "variables": "[MON SUJET], [MON AUDIENCE]",
    "example": "sujet \"configurer sa chaîne YouTube\" (voir Partie 04).",
    "result": "un développement de script clair, prêt à être illustré d'exemples."
  },
  {
    "id": 63,
    "category": "SCRIPTS",
    "title": "Pattern interrupt pour un script existant",
    "objective": "ajouter une rupture de rythme au milieu d'un script.",
    "when": "quand le script semble monotone au milieu.",
    "prompt": "Voici mon script : [SCRIPT]. Propose un pattern interrupt à insérer au milieu, sous forme de question directe ou d'anecdote.",
    "variables": "[SCRIPT]",
    "example": "script sans rupture de rythme identifiable.",
    "result": "une relance d'attention à insérer au bon endroit (voir Partie 06)."
  },
  {
    "id": 64,
    "category": "SCRIPTS",
    "title": "Transition entre deux parties",
    "objective": "relier logiquement deux blocs d'un script.",
    "when": "quand deux parties semblent mal connectées.",
    "prompt": "Écris une transition fluide entre cette partie : [PARTIE 1] et celle-ci : [PARTIE 2].",
    "variables": "[PARTIE 1], [PARTIE 2]",
    "example": "transition entre \"comment démarrer\" et \"ce qui fait la différence après\".",
    "result": "une transition qui évite l'effet \"morceaux collés\"."
  },
  {
    "id": 65,
    "category": "SCRIPTS",
    "title": "CTA lié à la valeur reçue",
    "objective": "générer un CTA cohérent avec le contenu de la vidéo.",
    "when": "à la fin de chaque script.",
    "prompt": "Voici le contenu principal de ma vidéo : [RÉSUMÉ]. Écris un CTA qui découle directement de cette valeur, sans être générique.",
    "variables": "[RÉSUMÉ]",
    "example": "vidéo sur les bases pour démarrer une chaîne.",
    "result": "un CTA spécifique plutôt qu'un \"like et abonne-toi\" générique (voir Partie 06)."
  },
  {
    "id": 66,
    "category": "SCRIPTS",
    "title": "Script version courte (Shorts)",
    "objective": "adapter un script long en version Shorts.",
    "when": "pour décliner un contenu long en format court.",
    "prompt": "Résume ce script en une version de 30-45 secondes adaptée au format Shorts, en gardant le point le plus percutant : [SCRIPT LONG].",
    "variables": "[SCRIPT LONG]",
    "example": "script long sur une erreur fréquente réduit à son point le plus fort.",
    "result": "un script Shorts concentré sur une seule idée forte."
  },
  {
    "id": 67,
    "category": "SCRIPTS",
    "title": "Script avec exemples intégrés",
    "objective": "enrichir un développement trop théorique avec des exemples.",
    "when": "quand le script manque de concret.",
    "prompt": "Voici mon développement : [DÉVELOPPEMENT]. Ajoute un exemple concret pour chaque idée abstraite mentionnée.",
    "variables": "[DÉVELOPPEMENT]",
    "example": "développement théorique sur la gestion du temps.",
    "result": "un script plus concret, conforme à la règle pédagogique du livre."
  },
  {
    "id": 68,
    "category": "SCRIPTS",
    "title": "Script pour chaîne sans visage",
    "objective": "adapter le rythme d'un script à une narration en voix off.",
    "when": "pour une chaîne sans présence à l'écran (Partie 08).",
    "prompt": "Adapte ce script pour une narration en voix off, avec un rythme plus soutenu et des indications de changements visuels : [SCRIPT].",
    "variables": "[SCRIPT]",
    "example": "script initialement pensé pour une présence filmée.",
    "result": "un script avec indications de rythme adaptées à l'absence de visage."
  },
  {
    "id": 69,
    "category": "SCRIPTS",
    "title": "Simplification d'un script trop technique",
    "objective": "rendre un script accessible à un public débutant.",
    "when": "quand le script contient trop de jargon.",
    "prompt": "Simplifie ce script pour un public débutant complet, en expliquant chaque terme technique au premier usage : [SCRIPT].",
    "variables": "[SCRIPT]",
    "example": "script sur un sujet technique (SEO, investissement, etc.).",
    "result": "un script conforme au niveau de lecteur visé par ce livre."
  },
  {
    "id": 70,
    "category": "SCRIPTS",
    "title": "Vérification de la structure en 9 blocs",
    "objective": "vérifier qu'un script contient bien les 9 blocs attendus.",
    "when": "en relecture finale avant tournage.",
    "prompt": "Analyse ce script et indique lequel des 9 blocs (Hook, Promesse, Introduction, Développement, Exemple, Pattern interrupt, Transition, Conclusion, CTA) semble manquant ou peu clair : [SCRIPT].",
    "variables": "[SCRIPT]",
    "example": "script incomplet sans pattern interrupt identifiable.",
    "result": "une checklist de relecture automatisée (voir checklist Partie 06)."
  },
  {
    "id": 71,
    "category": "SCRIPTS",
    "title": "Script à partir d'un cas pratique",
    "objective": "transformer un cas pratique du livre en script vidéo.",
    "when": "pour illustrer un concept avec une histoire.",
    "prompt": "Transforme ce cas pratique en script vidéo narratif : [DESCRIPTION DU CAS], destiné à [MON AUDIENCE].",
    "variables": "[DESCRIPTION DU CAS], [MON AUDIENCE]",
    "example": "cas Kevin ou Sarah (Parties 01-02) adaptés à ta propre niche.",
    "result": "un script narratif qui illustre une leçon par une histoire."
  },
  {
    "id": 72,
    "category": "SCRIPTS",
    "title": "Script orienté storytelling",
    "objective": "intégrer une structure narrative à un script informatif.",
    "when": "pour du contenu qui gagnerait à être raconté plutôt qu'expliqué.",
    "prompt": "Réécris ce contenu sous forme d'histoire avec un début, une difficulté et une résolution, sur le sujet [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet \"mon premier échec sur YouTube\" (voir Catégorie 7 — Storytelling).",
    "result": "un script plus engageant émotionnellement."
  },
  {
    "id": 73,
    "category": "SCRIPTS",
    "title": "Script de vidéo de présentation de chaîne",
    "objective": "rédiger le script de la vidéo d'accueil de la chaîne.",
    "when": "en lien avec la Partie 04.",
    "prompt": "Rédige un script de 1-2 minutes pour une vidéo de présentation de chaîne sur [MA NICHE], destinée à [MON AUDIENCE], avec mon positionnement : [MON POSITIONNEMENT].",
    "variables": "[MA NICHE], [MON AUDIENCE], [MON POSITIONNEMENT]",
    "example": "chaîne éducative avec positionnement clair (voir cas Amina).",
    "result": "un script court et efficace pour la page d'accueil de la chaîne."
  },
  {
    "id": 74,
    "category": "SCRIPTS",
    "title": "Réduction de la longueur d'un script",
    "objective": "condenser un script trop long sans perdre l'essentiel.",
    "when": "quand une vidéo dépasse la durée prévue.",
    "prompt": "Réduis ce script d'environ 30% en gardant le hook, la promesse et le CTA intacts : [SCRIPT].",
    "variables": "[SCRIPT]",
    "example": "script de 10 minutes à ramener à 7 minutes.",
    "result": "un script plus dense, sans perte de la structure essentielle."
  },
  {
    "id": 75,
    "category": "SCRIPTS",
    "title": "Script pour vidéo comparative",
    "objective": "structurer un script de type comparaison.",
    "when": "pour un contenu \"X vs Y\".",
    "prompt": "Rédige un script structuré pour une vidéo comparant [ÉLÉMENT A] et [ÉLÉMENT B], destinée à [MON AUDIENCE].",
    "variables": "[ÉLÉMENT A], [ÉLÉMENT B], [MON AUDIENCE]",
    "example": "comparaison de deux outils ou méthodes dans ta niche.",
    "result": "un script équilibré qui évite de favoriser artificiellement un côté."
  },
  {
    "id": 76,
    "category": "STORYTELLING",
    "title": "Structure narrative en 3 actes",
    "objective": "structurer une histoire en début, difficulté, résolution.",
    "when": "pour transformer un fait en récit engageant.",
    "prompt": "Structure cette histoire en 3 actes (situation initiale, difficulté, résolution) : [DESCRIPTION DES FAITS], en lien avec le sujet [MON SUJET].",
    "variables": "[DESCRIPTION DES FAITS], [MON SUJET]",
    "example": "parcours d'un des cas pratiques du livre (ex. échec et rebond, Partie 14).",
    "result": "une trame narrative claire à intégrer dans un script."
  },
  {
    "id": 77,
    "category": "STORYTELLING",
    "title": "Storytelling à partir d'un échec",
    "objective": "transformer un échec personnel en récit utile pour l'audience.",
    "when": "pour renforcer l'authenticité et la confiance.",
    "prompt": "Transforme cet échec personnel en récit avec une leçon claire pour [MON AUDIENCE] : [DESCRIPTION DE L'ÉCHEC].",
    "variables": "[DESCRIPTION DE L'ÉCHEC], [MON AUDIENCE]",
    "example": "premier lancement de chaîne raté (voir cas \"échec et rebond\").",
    "result": "un récit qui installe la confiance avant de délivrer un conseil."
  },
  {
    "id": 78,
    "category": "STORYTELLING",
    "title": "Tension narrative pour maintenir l'attention",
    "objective": "créer une tension qui se maintient jusqu'à la résolution.",
    "when": "pour éviter qu'un récit ne s'essouffle au milieu.",
    "prompt": "Ajoute un élément de tension ou de suspense à ce récit, sans en révéler la résolution trop tôt : [RÉCIT].",
    "variables": "[RÉCIT]",
    "example": "récit qui dévoile sa conclusion trop rapidement.",
    "result": "un récit qui maintient l'attention jusqu'à la fin."
  },
  {
    "id": 79,
    "category": "STORYTELLING",
    "title": "Personnage archétype pour illustrer un concept",
    "objective": "créer un personnage fictif pour illustrer une idée (sur le modèle des cas du livre).",
    "when": "pour rendre un concept abstrait plus concret.",
    "prompt": "Crée un personnage fictif représentatif de [MON AUDIENCE] pour illustrer le concept suivant : [CONCEPT], en précisant que c'est un cas fictif pédagogique.",
    "variables": "[MON AUDIENCE], [CONCEPT]",
    "example": "un personnage pour illustrer une erreur fréquente de niche (voir cas Kevin, Sarah, Patrick).",
    "result": "une illustration concrète, clairement présentée comme fictive."
  },
  {
    "id": 80,
    "category": "STORYTELLING",
    "title": "Storytelling produit ou service",
    "objective": "raconter l'histoire d'un produit ou service plutôt que de le lister.",
    "when": "pour du contenu e-commerce ou services (Partie 12).",
    "prompt": "Raconte l'histoire de l'utilisation de [PRODUIT/SERVICE] par un client type, plutôt que d'en lister les caractéristiques.",
    "variables": "[PRODUIT/SERVICE]",
    "example": "produit e-commerce présenté à travers un cas d'usage réel.",
    "result": "un récit plus convaincant qu'une simple fiche produit (voir Modèle 6, Partie 12)."
  },
  {
    "id": 81,
    "category": "STORYTELLING",
    "title": "Storytelling pour la vidéo de présentation",
    "objective": "intégrer un récit personnel dans la vidéo de présentation de chaîne.",
    "when": "en complément du Prompt N°73 (Catégorie 6).",
    "prompt": "Intègre un court récit personnel de mon parcours dans une vidéo de présentation sur [MA NICHE], sans que cela prenne plus de 30 secondes.",
    "variables": "[MA NICHE]",
    "example": "parcours personnel amenant à la niche choisie.",
    "result": "une vidéo de présentation plus humaine et mémorable."
  },
  {
    "id": 82,
    "category": "STORYTELLING",
    "title": "Analogie pour expliquer un concept complexe",
    "objective": "simplifier un concept abstrait via une analogie.",
    "when": "pour la vulgarisation d'un sujet technique.",
    "prompt": "Trouve une analogie simple et concrète pour expliquer le concept suivant à un débutant : [CONCEPT].",
    "variables": "[CONCEPT]",
    "example": "expliquer l'algorithme YouTube (Partie 01) avec une analogie du quotidien.",
    "result": "une explication plus accessible pour l'audience visée."
  },
  {
    "id": 83,
    "category": "STORYTELLING",
    "title": "Récit clientèle (témoignage fictif pédagogique)",
    "objective": "illustrer un résultat par un témoignage-type.",
    "when": "pour illustrer un modèle de monétisation (Partie 12), en gardant l'honnêteté du contenu.",
    "prompt": "Rédige un témoignage-type, clairement présenté comme un exemple fictif pédagogique, illustrant un résultat réaliste (non garanti) obtenu grâce à [OFFRE/MÉTHODE].",
    "variables": "[OFFRE/MÉTHODE]",
    "example": "illustration réaliste d'un des 9 modèles de monétisation.",
    "result": "une illustration honnête, jamais présentée comme une promesse de résultat."
  },
  {
    "id": 84,
    "category": "STORYTELLING",
    "title": "Storytelling pour introduire une checklist",
    "objective": "donner du contexte narratif avant de présenter une liste ou une checklist.",
    "when": "pour éviter qu'une checklist tombe \"à froid\" dans une vidéo.",
    "prompt": "Écris une courte mise en situation narrative qui amène naturellement vers la checklist suivante : [CHECKLIST].",
    "variables": "[CHECKLIST]",
    "example": "mise en situation avant la checklist de publication (Partie 08).",
    "result": "une transition plus fluide entre récit et contenu pratique."
  },
  {
    "id": 85,
    "category": "STORYTELLING",
    "title": "Récit de transformation sur la durée",
    "objective": "illustrer une progression dans le temps (avant/pendant/après).",
    "when": "pour du contenu de type bilan ou évolution.",
    "prompt": "Structure un récit de transformation en 3 étapes (avant, pendant, après) sur le sujet [MON SUJET], pour [MON AUDIENCE].",
    "variables": "[MON SUJET], [MON AUDIENCE]",
    "example": "évolution d'une chaîne sur plusieurs mois (voir Plan 90 jours, Partie 15).",
    "result": "un récit qui donne une perspective claire de progression réaliste."
  },
  {
    "id": 86,
    "category": "SHORTS",
    "title": "Idée de Short à partir d'une vidéo longue",
    "objective": "extraire le meilleur moment d'une vidéo longue pour un Short.",
    "when": "après la publication d'une vidéo longue.",
    "prompt": "Voici le résumé de ma vidéo longue : [RÉSUMÉ]. Identifie le moment le plus percutant à décliner en Short.",
    "variables": "[RÉSUMÉ]",
    "example": "moment fort d'un script (voir Prompt N°32, Catégorie 3).",
    "result": "une idée de Short directement extraite d'un contenu existant."
  },
  {
    "id": 87,
    "category": "SHORTS",
    "title": "Script de Short en une idée unique",
    "objective": "rédiger un script de Short centré sur une seule idée.",
    "when": "pour respecter la contrainte de format court.",
    "prompt": "Rédige un script de Short (30-45 secondes) centré sur une seule idée forte : [IDÉE], pour [MON AUDIENCE].",
    "variables": "[IDÉE], [MON AUDIENCE]",
    "example": "une seule erreur fréquente développée en profondeur, sans digression.",
    "result": "un script resserré, sans les 9 blocs complets d'un script long."
  },
  {
    "id": 88,
    "category": "SHORTS",
    "title": "Accroche ultra-rapide pour Short",
    "objective": "capter l'attention en 1-2 secondes.",
    "when": "en lien avec le Prompt N°57 (Catégorie 5).",
    "prompt": "Écris une accroche de Short qui capte l'attention en moins de 2 secondes, sur le sujet [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "accroche visuelle et verbale combinée dès la première image.",
    "result": "une accroche adaptée à la tolérance très faible du format Shorts (voir Partie 09)."
  },
  {
    "id": 89,
    "category": "SHORTS",
    "title": "Série de Shorts sur un même thème",
    "objective": "décliner un thème en plusieurs Shorts complémentaires.",
    "when": "pour alimenter une régularité de publication de Shorts.",
    "prompt": "Décline le thème [THÈME] en 5 Shorts distincts, chacun centré sur un sous-aspect différent.",
    "variables": "[THÈME]",
    "example": "thème \"erreurs en photographie\" décliné en 5 Shorts, un par erreur.",
    "result": "une série cohérente facilitant la régularité (voir Partie 10)."
  },
  {
    "id": 90,
    "category": "SHORTS",
    "title": "Texte à l'écran pour Short",
    "objective": "générer un texte overlay percutant et court.",
    "when": "pour renforcer la compréhension sans le son.",
    "prompt": "Propose un texte à l'écran de 3-6 mots maximum pour accompagner ce Short : [DESCRIPTION DU SHORT].",
    "variables": "[DESCRIPTION DU SHORT]",
    "example": "Short sur une astuce rapide, avec texte résumant l'astuce.",
    "result": "un texte lisible même sans le son activé."
  },
  {
    "id": 91,
    "category": "SHORTS",
    "title": "CTA adapté au format Short",
    "objective": "rédiger un CTA cohérent avec la brièveté du format.",
    "when": "à la fin d'un script de Short.",
    "prompt": "Écris un CTA très court (une phrase) adapté à un Short sur le sujet [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "CTA redirigeant vers la vidéo longue correspondante.",
    "result": "un CTA qui ne casse pas le rythme rapide du format."
  },
  {
    "id": 92,
    "category": "SHORTS",
    "title": "Transformation d'un Short en vidéo longue",
    "objective": "développer un Short qui a bien fonctionné en contenu plus long.",
    "when": "après avoir identifié un Short performant.",
    "prompt": "Voici le script d'un Short qui a bien fonctionné : [SCRIPT SHORT]. Propose une structure de vidéo longue qui développe cette même idée.",
    "variables": "[SCRIPT SHORT]",
    "example": "un Short populaire développé en tutoriel complet.",
    "result": "une stratégie de contenu croisée entre formats courts et longs."
  },
  {
    "id": 93,
    "category": "SHORTS",
    "title": "Idée de Short à partir d'une question fréquente",
    "objective": "transformer une question fréquente en Short direct.",
    "when": "pour répondre rapidement à des interrogations récurrentes.",
    "prompt": "Transforme cette question fréquente en script de Short avec une réponse directe et concise : [QUESTION].",
    "variables": "[QUESTION]",
    "example": "question tirée du Prompt N°12 (Catégorie 2).",
    "result": "un Short qui répond immédiatement sans détour."
  },
  {
    "id": 94,
    "category": "SHORTS",
    "title": "Rythme de montage pour Short",
    "objective": "obtenir des indications de rythme de montage adaptées au format.",
    "when": "en préparation du montage (Partie 08).",
    "prompt": "Propose des indications de rythme de montage (fréquence de coupe, effets) adaptées à un Short sur [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet nécessitant un rythme très soutenu pour maintenir l'attention.",
    "result": "des indications concrètes à transmettre à la phase de montage."
  },
  {
    "id": 95,
    "category": "SHORTS",
    "title": "Calendrier de Shorts complémentaire",
    "objective": "intégrer les Shorts dans le calendrier de contenu global.",
    "when": "en lien avec la Partie 10.",
    "prompt": "Propose un calendrier de 4 semaines combinant 1 vidéo longue et 3 Shorts complémentaires par semaine, sur la niche [MA NICHE].",
    "variables": "[MA NICHE]",
    "example": "niche \"fitness à domicile\".",
    "result": "un calendrier équilibré entre formats longs et courts."
  },
  {
    "id": 96,
    "category": "SEO",
    "title": "Mots-clés réels de l'audience",
    "objective": "identifier les formulations exactes tapées par l'audience.",
    "when": "Partie 09, Exercice 11.",
    "prompt": "Liste 10 formulations exactes que [MON AUDIENCE] pourrait taper dans la barre de recherche YouTube pour trouver du contenu sur [MON SUJET].",
    "variables": "[MON AUDIENCE], [MON SUJET]",
    "example": "audience \"débutants en jardinage\", sujet \"entretien d'un potager\".",
    "result": "une base de mots-clés à intégrer au titre et à la description."
  },
  {
    "id": 97,
    "category": "SEO",
    "title": "Description optimisée",
    "objective": "rédiger une description qui intègre naturellement les mots-clés principaux.",
    "when": "après la finalisation du script.",
    "prompt": "Rédige une description YouTube pour une vidéo sur [MON SUJET], avec les mots-clés [LISTE DE MOTS-CLÉS] intégrés naturellement dans les 2 premières lignes.",
    "variables": "[MON SUJET], [LISTE DE MOTS-CLÉS]",
    "example": "vidéo sur la gestion du stress, mots-clés associés.",
    "result": "une description conforme aux principes de la Partie 09."
  },
  {
    "id": 98,
    "category": "SEO",
    "title": "Liste de chapitres",
    "objective": "structurer une vidéo en chapitres clairs.",
    "when": "pour les vidéos de plus de 5-6 minutes.",
    "prompt": "À partir de ce script : [SCRIPT], propose une liste de chapitres avec des titres courts et clairs.",
    "variables": "[SCRIPT]",
    "example": "script structuré en plusieurs étapes numérotées.",
    "result": "des chapitres prêts à intégrer dans la description YouTube."
  },
  {
    "id": 99,
    "category": "SEO",
    "title": "Variantes de tags",
    "objective": "générer des tags couvrant les variantes du sujet.",
    "when": "en complément du titre et de la description.",
    "prompt": "Propose 15 tags pertinents, incluant des variantes orthographiques et des termes proches, pour une vidéo sur [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet avec plusieurs formulations possibles (ex. \"chaîne YouTube\" / \"chaine youtube\").",
    "result": "une liste de tags à copier directement dans les paramètres de la vidéo."
  },
  {
    "id": 100,
    "category": "SEO",
    "title": "Analyse de mots-clés d'un concurrent",
    "objective": "identifier les mots-clés probablement utilisés par une vidéo concurrente performante.",
    "when": "en lien avec la Partie 03.",
    "prompt": "Voici le titre et la description d'une vidéo concurrente performante : [TITRE ET DESCRIPTION]. Quels mots-clés semble-t-elle cibler ?",
    "variables": "[TITRE ET DESCRIPTION]",
    "example": "vidéo bien classée sur un sujet proche du tien.",
    "result": "des pistes de mots-clés à intégrer dans ta propre stratégie SEO."
  },
  {
    "id": 101,
    "category": "SEO",
    "title": "Première phrase parlée optimisée",
    "objective": "intégrer un mot-clé naturellement dans les premières secondes parlées.",
    "when": "lors de la rédaction du script (Partie 06).",
    "prompt": "Réécris cette introduction pour y intégrer naturellement le mot-clé [MOT-CLÉ], sans que cela sonne artificiel : [INTRODUCTION].",
    "variables": "[MOT-CLÉ], [INTRODUCTION]",
    "example": "introduction générique reformulée avec un mot-clé précis.",
    "result": "une introduction qui reste naturelle tout en aidant au référencement."
  },
  {
    "id": 102,
    "category": "SEO",
    "title": "Titre alternatif orienté recherche",
    "objective": "proposer un titre plus aligné avec les recherches réelles, sans perdre en accroche.",
    "when": "en complément de la Catégorie 4 (Titres).",
    "prompt": "Voici un titre accrocheur : [TITRE]. Propose une version qui intègre davantage le mot-clé [MOT-CLÉ] recherché, sans perdre en attractivité.",
    "variables": "[TITRE], [MOT-CLÉ]",
    "example": "équilibre entre accroche et référencement.",
    "result": "un titre qui combine les deux objectifs (Partie 05 et 09)."
  },
  {
    "id": 103,
    "category": "SEO",
    "title": "Audit SEO rapide d'une vidéo existante",
    "objective": "identifier les points d'amélioration SEO d'une vidéo déjà publiée.",
    "when": "en révision périodique de contenu ancien.",
    "prompt": "Voici le titre, la description et les premières phrases de ma vidéo : [ÉLÉMENTS]. Identifie les opportunités d'amélioration SEO.",
    "variables": "[ÉLÉMENTS]",
    "example": "ancienne vidéo avec une description vide (voir erreurs fréquentes, Partie 09).",
    "result": "une liste d'actions correctives concrètes."
  },
  {
    "id": 104,
    "category": "SEO",
    "title": "Mots-clés longue traîne",
    "objective": "identifier des recherches plus spécifiques et moins concurrentielles.",
    "when": "pour une chaîne encore récente, en complément des mots-clés génériques.",
    "prompt": "Propose 10 mots-clés \"longue traîne\" (recherches précises et moins concurrentielles) liés à [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "sujet large \"productivité\" variantes précises et moins disputées.",
    "result": "des opportunités de référencement plus accessibles en début de chaîne."
  },
  {
    "id": 105,
    "category": "SEO",
    "title": "Cohérence SEO entre titre, description et tags",
    "objective": "vérifier que les trois éléments SEO se renforcent mutuellement.",
    "when": "en vérification finale avant publication.",
    "prompt": "Vérifie la cohérence entre ce titre : [TITRE], cette description : [DESCRIPTION] et ces tags : [TAGS]. Signale les incohérences ou répétitions inutiles.",
    "variables": "[TITRE], [DESCRIPTION], [TAGS]",
    "example": "titre et description ciblant des mots-clés différents et non complémentaires.",
    "result": "un ensemble SEO cohérent avant la mise en ligne."
  },
  {
    "id": 106,
    "category": "DESCRIPTIONS",
    "title": "Description complète structurée",
    "objective": "rédiger une description complète, au-delà des 2 premières lignes.",
    "when": "juste avant publication.",
    "prompt": "Rédige une description YouTube complète pour une vidéo sur [MON SUJET] : 2 premières lignes optimisées SEO, résumé du contenu, liens utiles, et mention de la régularité de publication.",
    "variables": "[MON SUJET]",
    "example": "vidéo sur les bases du montage vidéo.",
    "result": "une description structurée conforme aux principes de la Partie 09."
  },
  {
    "id": 107,
    "category": "DESCRIPTIONS",
    "title": "Description pour vidéo de service",
    "objective": "intégrer un appel à l'action commercial de façon naturelle dans la description.",
    "when": "pour du contenu lié aux Modèles 3 et 7 (Partie 12).",
    "prompt": "Rédige une description pour une vidéo sur [MON SUJET], incluant une mention discrète de mon offre de [TYPE D'OFFRE] en fin de description.",
    "variables": "[MON SUJET], [TYPE D'OFFRE]",
    "example": "vidéo de coaching sportif (voir cas David) avec mention de l'offre en fin de texte.",
    "result": "une description qui informe sans être intrusive."
  },
  {
    "id": 108,
    "category": "DESCRIPTIONS",
    "title": "Description multilingue",
    "objective": "adapter une description pour un contenu bilingue.",
    "when": "en lien avec la Partie 13 (YouTube depuis l'Afrique).",
    "prompt": "Rédige une description bilingue (français et [LANGUE LOCALE]) pour une vidéo sur [MON SUJET].",
    "variables": "[LANGUE LOCALE], [MON SUJET]",
    "example": "description en français et dans une langue locale pertinente pour l'audience visée.",
    "result": "une description accessible aux deux publics visés."
  },
  {
    "id": 109,
    "category": "DESCRIPTIONS",
    "title": "Description avec liens d'affiliation",
    "objective": "intégrer des liens d'affiliation de façon transparente.",
    "when": "en lien avec le Modèle 2 (Partie 12).",
    "prompt": "Rédige une description mentionnant clairement des liens affiliés pour les produits suivants : [LISTE DE PRODUITS], en respectant la transparence envers l'audience.",
    "variables": "[LISTE DE PRODUITS]",
    "example": "vidéo test de matériel avec liens affiliés associés.",
    "result": "une description honnête, qui protège la confiance de l'audience."
  },
  {
    "id": 110,
    "category": "DESCRIPTIONS",
    "title": "Description courte pour Short",
    "objective": "rédiger une description adaptée à la brièveté d'un Short.",
    "when": "pour la Catégorie 8 (Shorts).",
    "prompt": "Rédige une description courte (1-2 lignes) pour un Short sur [MON SUJET], avec un mot-clé principal intégré.",
    "variables": "[MON SUJET]",
    "example": "Short sur une astuce ponctuelle.",
    "result": "une description brève mais toujours utile au référencement."
  },
  {
    "id": 111,
    "category": "MINIATURES",
    "title": "Concept de miniature à partir d'un titre",
    "objective": "générer un concept visuel cohérent avec un titre.",
    "when": "Partie 07, Exercice 10.",
    "prompt": "Voici mon titre : [TITRE]. Décris un concept de miniature avec émotion, élément principal, texte court et composition.",
    "variables": "[TITRE]",
    "example": "titre \"Comment gagner ses premiers 1000 abonnés\" (voir corrigé Partie 07).",
    "result": "un concept détaillé, prêt à transmettre à un graphiste ou à un outil de génération d'image."
  },
  {
    "id": 112,
    "category": "MINIATURES",
    "title": "Texte court pour miniature",
    "objective": "générer un texte overlay de 3-5 mots maximum.",
    "when": "après validation du concept visuel.",
    "prompt": "Propose 5 textes courts (3-5 mots maximum) pour une miniature sur le sujet [MON SUJET], qui complètent le titre sans le répéter.",
    "variables": "[MON SUJET]",
    "example": "sujet \"erreurs en photographie\".",
    "result": "des textes courts et percutants à tester en miniature."
  },
  {
    "id": 113,
    "category": "MINIATURES",
    "title": "Émotion à représenter",
    "objective": "identifier l'émotion la plus adaptée à une miniature.",
    "when": "en amont de la composition visuelle.",
    "prompt": "Quelle émotion faciale serait la plus efficace pour une miniature sur [MON SUJET], destinée à [MON AUDIENCE] ? Justifie brièvement.",
    "variables": "[MON SUJET], [MON AUDIENCE]",
    "example": "sujet anxiogène nécessitant une émotion de doute plutôt que de peur excessive.",
    "result": "une direction claire pour le tournage ou la sélection de l'image."
  },
  {
    "id": 114,
    "category": "MINIATURES",
    "title": "Palette de couleurs cohérente",
    "objective": "proposer une palette de couleurs pour renforcer l'identité visuelle.",
    "when": "pour garder une cohérence entre les miniatures d'une chaîne.",
    "prompt": "Propose une palette de 3 couleurs dominantes pour les miniatures d'une chaîne sur [MA NICHE], cohérente avec le positionnement [MON POSITIONNEMENT].",
    "variables": "[MA NICHE], [MON POSITIONNEMENT]",
    "example": "positionnement \"voyage petit budget\" palette évoquant la simplicité et l'accessibilité.",
    "result": "une base de direction artistique reconnaissable (voir Partie 07)."
  },
  {
    "id": 115,
    "category": "MINIATURES",
    "title": "Vérification de lisibilité mobile",
    "objective": "anticiper la lisibilité d'une miniature en petit format.",
    "when": "avant publication.",
    "prompt": "Voici la description de ma miniature : [DESCRIPTION]. Cette composition reste-t-elle lisible réduite à la taille d'une vignette mobile ? Que simplifier ?",
    "variables": "[DESCRIPTION]",
    "example": "miniature avec trop d'éléments superposés.",
    "result": "des suggestions de simplification (voir checklist Partie 07)."
  },
  {
    "id": 116,
    "category": "MINIATURES",
    "title": "Miniature cohérente avec une série",
    "objective": "garder une cohérence visuelle sur une série de vidéos.",
    "when": "pour une série ou un format récurrent (voir Prompt N°28).",
    "prompt": "Propose un gabarit de composition de miniature réutilisable pour la série [NOM DE LA SÉRIE], avec des éléments fixes et des éléments variables.",
    "variables": "[NOM DE LA SÉRIE]",
    "example": "série hebdomadaire \"1 recette, 3 ingrédients\".",
    "result": "un gabarit qui accélère la production tout en gardant une identité reconnaissable."
  },
  {
    "id": 117,
    "category": "MINIATURES",
    "title": "Concept de miniature pour vidéo comparative",
    "objective": "représenter visuellement une comparaison.",
    "when": "pour une vidéo de type \"X vs Y\".",
    "prompt": "Propose un concept de miniature pour une vidéo comparant [ÉLÉMENT A] et [ÉLÉMENT B].",
    "variables": "[ÉLÉMENT A], [ÉLÉMENT B]",
    "example": "comparaison de deux outils ou méthodes.",
    "result": "une composition qui montre clairement l'opposition entre les deux éléments."
  },
  {
    "id": 118,
    "category": "MINIATURES",
    "title": "Concept de miniature avant/après",
    "objective": "représenter visuellement une transformation.",
    "when": "pour du contenu à résultat visible.",
    "prompt": "Propose un concept de miniature en deux parties (avant/après) pour une vidéo sur [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "transformation d'un espace, d'un résultat physique, ou d'un projet.",
    "result": "une composition qui suggère immédiatement un résultat concret."
  },
  {
    "id": 119,
    "category": "MINIATURES",
    "title": "Alternative de miniature sans visage",
    "objective": "concevoir une miniature efficace sans utiliser de visage.",
    "when": "pour une chaîne sans visage (Partie 08).",
    "prompt": "Propose un concept de miniature efficace sans utiliser de visage humain, pour une vidéo sur [MON SUJET].",
    "variables": "[MON SUJET]",
    "example": "miniature basée sur un objet, un chiffre ou une composition graphique forte.",
    "result": "un concept qui compense l'absence de visage par un autre point focal fort."
  },
  {
    "id": 120,
    "category": "MINIATURES",
    "title": "Vérification d'exagération visuelle",
    "objective": "s'assurer que la miniature ne promet pas plus que le contenu réel.",
    "when": "en vérification finale, en lien avec le Prompt N°41.",
    "prompt": "Voici la description de ma miniature : [DESCRIPTION] et le contenu réel de ma vidéo : [RÉSUMÉ]. Cette miniature exagère-t-elle par rapport au contenu ?",
    "variables": "[DESCRIPTION], [RÉSUMÉ]",
    "example": "miniature suggérant un résultat extrême non représentatif du contenu réel.",
    "result": "une alerte avant publication pour protéger la confiance de l'audience."
  },
  {
    "id": 121,
    "category": "MINIATURES",
    "title": "Composition avec espace négatif",
    "objective": "optimiser la répartition des éléments dans le cadre.",
    "when": "pour éviter une miniature surchargée.",
    "prompt": "Propose une composition avec un espace négatif suffisant pour une miniature avec [ÉLÉMENT PRINCIPAL] et le texte [TEXTE].",
    "variables": "[ÉLÉMENT PRINCIPAL], [TEXTE]",
    "example": "visage en gros plan avec espace réservé pour un texte court.",
    "result": "une composition aérée et lisible (voir section 7.2)."
  },
  {
    "id": 122,
    "category": "MINIATURES",
    "title": "Miniature pour cas pratique/étude de cas",
    "objective": "représenter visuellement un cas pratique ou une étude de cas.",
    "when": "pour du contenu narratif basé sur un cas concret.",
    "prompt": "Propose un concept de miniature pour une vidéo présentant le cas pratique suivant : [RÉSUMÉ DU CAS].",
    "variables": "[RÉSUMÉ DU CAS]",
    "example": "un des cas pratiques du livre (Kevin, Sarah, Patrick...).",
    "result": "une miniature qui suggère une histoire plutôt qu'un simple conseil."
  },
  {
    "id": 123,
    "category": "MINIATURES",
    "title": "Test de contraste",
    "objective": "vérifier le contraste entre l'élément principal et l'arrière-plan.",
    "when": "en relecture avant publication.",
    "prompt": "Voici la description de ma miniature : [DESCRIPTION]. Le contraste entre l'élément principal et l'arrière-plan est-il suffisant pour se détacher en petit format ?",
    "variables": "[DESCRIPTION]",
    "example": "élément principal de couleur proche de l'arrière-plan.",
    "result": "une recommandation d'ajustement de contraste."
  },
  {
    "id": 124,
    "category": "MINIATURES",
    "title": "Direction artistique cohérente avec l'IA",
    "objective": "garder une identité visuelle propre même en utilisant des outils IA.",
    "when": "en lien avec la section 7.3 sur la direction artistique humaine.",
    "prompt": "Je veux utiliser un outil de génération d'image IA pour ma miniature, tout en gardant mon identité visuelle habituelle : [DESCRIPTION DE L'IDENTITÉ VISUELLE]. Comment formuler un prompt de génération d'image qui respecte cette identité ?",
    "variables": "[DESCRIPTION DE L'IDENTITÉ VISUELLE]",
    "example": "palette de couleurs et style habituels de la chaîne.",
    "result": "un prompt de génération d'image qui reste cohérent avec l'identité de la chaîne, sans tomber dans le générique."
  },
  {
    "id": 125,
    "category": "MINIATURES",
    "title": "Idées de miniature pour une série de Bonus",
    "objective": "concevoir des miniatures cohérentes pour du contenu bonus ou une checklist visuelle.",
    "when": "pour la Partie 18 (Bonus) de ce livre ou un contenu équivalent.",
    "prompt": "Propose un concept de miniature pour une ressource bonus intitulée [NOM DU BONUS].",
    "variables": "[NOM DU BONUS]",
    "example": "bonus \"100 idées de vidéos\" ou \"30 hooks\".",
    "result": "une miniature qui valorise visuellement une ressource pratique."
  },
  {
    "id": 126,
    "category": "ANALYSE DE CONCURRENCE",
    "title": "Tableau comparatif de concurrents",
    "objective": "structurer l'observation de plusieurs concurrents.",
    "when": "Partie 03, Exercice 5.",
    "prompt": "Structure une comparaison de ces concurrents : [LISTE DE CHAÎNES], selon les critères : positionnement, format dominant, fréquence, point fort, opportunité non couverte.",
    "variables": "[LISTE DE CHAÎNES]",
    "example": "3 chaînes dans une même niche.",
    "result": "un tableau à remplir avec des observations réelles."
  },
  {
    "id": 127,
    "category": "ANALYSE DE CONCURRENCE",
    "title": "Identification d'un espace libre",
    "objective": "identifier un angle non couvert par la concurrence.",
    "when": "après avoir observé plusieurs concurrents.",
    "prompt": "Voici les angles couverts par mes concurrents : [LISTE DES ANGLES]. Quel espace semble libre dans cette niche ?",
    "variables": "[LISTE DES ANGLES]",
    "example": "voir cas Patrick (Partie 03).",
    "result": "une piste de différenciation à valider par une observation complémentaire."
  },
  {
    "id": 128,
    "category": "ANALYSE DE CONCURRENCE",
    "title": "Analyse des commentaires d'un concurrent",
    "objective": "extraire des idées de contenu à partir des commentaires d'une chaîne concurrente.",
    "when": "en complément de l'analyse structurelle.",
    "prompt": "Voici une sélection de commentaires sur une vidéo concurrente : [COMMENTAIRES]. Quelles questions ou frustrations non résolues en ressortent ?",
    "variables": "[COMMENTAIRES]",
    "example": "commentaires révélant un besoin non couvert par le créateur.",
    "result": "des idées de contenu directement issues d'une demande non satisfaite."
  },
  {
    "id": 129,
    "category": "ANALYSE DE CONCURRENCE",
    "title": "Comparaison de formats de titre",
    "objective": "identifier des schémas récurrents dans les titres d'un concurrent.",
    "when": "pour s'inspirer sans copier.",
    "prompt": "Voici une liste de titres d'une chaîne concurrente performante : [LISTE DE TITRES]. Quels schémas ou structures reviennent souvent ?",
    "variables": "[LISTE DE TITRES]",
    "example": "titres suivant systématiquement une structure question/chiffre.",
    "result": "des principes à adapter à son propre style, jamais à copier mot pour mot."
  },
  {
    "id": 130,
    "category": "ANALYSE DE CONCURRENCE",
    "title": "Veille périodique de la concurrence",
    "objective": "préparer une routine simple de veille concurrentielle.",
    "when": "pour un suivi régulier sans y consacrer trop de temps.",
    "prompt": "Propose une méthode simple pour suivre mensuellement l'évolution de 3 concurrents dans ma niche [MA NICHE], sans y passer plus de 30 minutes.",
    "variables": "[MA NICHE]",
    "example": "niche à forte évolution, nécessitant une veille régulière.",
    "result": "une routine de veille légère et soutenable."
  },
  {
    "id": 131,
    "category": "ANALYTICS",
    "title": "Diagnostic croisé de métriques",
    "objective": "obtenir une aide au diagnostic à partir de plusieurs métriques.",
    "when": "Partie 11, Exercice 13.",
    "prompt": "Voici les statistiques de ma vidéo : impressions [X], CTR [Y]%, rétention moyenne [Z]%. Quel diagnostic peux-tu en tirer, et quelle action tester en priorité ?",
    "variables": "[X], [Y], [Z]",
    "example": "cas 1 ou cas 2 de la Partie 11.",
    "result": "un diagnostic à confronter à la méthode déjà apprise dans ce livre."
  },
  {
    "id": 132,
    "category": "ANALYTICS",
    "title": "Comparaison entre deux vidéos",
    "objective": "comprendre pourquoi une vidéo performe mieux qu'une autre.",
    "when": "pour identifier un facteur de succès reproductible.",
    "prompt": "Compare ces deux vidéos : [STATISTIQUES VIDÉO A] et [STATISTIQUES VIDÉO B]. Quels facteurs expliquent probablement l'écart de performance ?",
    "variables": "[STATISTIQUES VIDÉO A], [STATISTIQUES VIDÉO B]",
    "example": "deux vidéos sur un sujet proche avec des résultats différents.",
    "result": "une hypothèse à tester sur les prochaines vidéos."
  },
  {
    "id": 133,
    "category": "ANALYTICS",
    "title": "Analyse de la rétention seconde par seconde",
    "objective": "identifier les moments précis de décrochage.",
    "when": "en lien avec le pattern interrupt (Partie 06).",
    "prompt": "Voici les moments où ma courbe de rétention chute significativement : [MOMENTS/TIMESTAMPS]. Quelles causes probables et quelles corrections tester ?",
    "variables": "[MOMENTS/TIMESTAMPS]",
    "example": "chute identifiée juste après l'introduction, ou au milieu de la vidéo.",
    "result": "une piste de correction ciblée (script, montage, ou pattern interrupt)."
  },
  {
    "id": 134,
    "category": "ANALYTICS",
    "title": "Bilan mensuel de chaîne",
    "objective": "synthétiser les performances du mois pour ajuster la stratégie.",
    "when": "en fin de mois, en lien avec le Plan 30/60/90 jours (Partie 15).",
    "prompt": "Voici mes statistiques du mois : [RÉSUMÉ DES STATISTIQUES]. Aide-moi à identifier 2 axes d'amélioration prioritaires pour le mois suivant.",
    "variables": "[RÉSUMÉ DES STATISTIQUES]",
    "example": "bilan mensuel comparé au mois précédent.",
    "result": "une synthèse actionnable plutôt qu'une simple liste de chiffres."
  },
  {
    "id": 135,
    "category": "ANALYTICS",
    "title": "Interprétation d'une source de trafic",
    "objective": "comprendre d'où provient l'audience d'une vidéo.",
    "when": "pour ajuster sa stratégie de découvrabilité.",
    "prompt": "Voici la répartition des sources de trafic de ma vidéo : [RÉPARTITION]. Que suggère cette répartition sur la façon dont ma vidéo est découverte ?",
    "variables": "[RÉPARTITION]",
    "example": "trafic majoritairement issu de la recherche vs des suggestions.",
    "result": "une meilleure compréhension de ce qui fonctionne (SEO vs recommandation algorithmique)."
  },
  {
    "id": 136,
    "category": "CALENDRIER ÉDITORIAL",
    "title": "Calendrier mensuel structuré",
    "objective": "générer un calendrier complet pour le mois à venir.",
    "when": "Partie 10, Exercice 12.",
    "prompt": "Construis un calendrier éditorial pour 4 semaines sur la niche [MA NICHE], avec pour chaque semaine : sujet, format (long/Short), et statut de production.",
    "variables": "[MA NICHE]",
    "example": "niche \"éducation financière\".",
    "result": "un calendrier prêt à transférer dans le tableau de la Partie 10."
  },
  {
    "id": 137,
    "category": "CALENDRIER ÉDITORIAL",
    "title": "Répartition des formats de contenu",
    "objective": "équilibrer les types de vidéos sur une période donnée.",
    "when": "pour éviter la monotonie de format.",
    "prompt": "Pour 8 vidéos à venir sur [MA NICHE], propose une répartition équilibrée entre questions fréquentes, comparaisons, erreurs communes et études de cas.",
    "variables": "[MA NICHE]",
    "example": "niche \"photographie\".",
    "result": "un calendrier varié qui évite la répétition d'un même format."
  },
  {
    "id": 138,
    "category": "CALENDRIER ÉDITORIAL",
    "title": "Ajustement du calendrier après un imprévu",
    "objective": "replanifier rapidement après un retard de production.",
    "when": "en cas de semaine chargée ou d'imprévu.",
    "prompt": "J'ai pris du retard sur mon calendrier : [DESCRIPTION DU RETARD]. Propose un calendrier ajusté pour les 2 prochaines semaines, réaliste par rapport à ce contretemps.",
    "variables": "[DESCRIPTION DU RETARD]",
    "example": "semaine chargée ayant empêché la production prévue.",
    "result": "un ajustement réaliste plutôt qu'un abandon du calendrier (voir erreurs fréquentes, Partie 10)."
  },
  {
    "id": 139,
    "category": "CALENDRIER ÉDITORIAL",
    "title": "Calendrier autour d'un lancement",
    "objective": "planifier le contenu autour du lancement d'une offre.",
    "when": "en lien avec la Partie 12 (monétisation).",
    "prompt": "Propose un calendrier de 3 semaines de contenu gratuit qui prépare progressivement le lancement de mon offre de [TYPE D'OFFRE].",
    "variables": "[TYPE D'OFFRE]",
    "example": "lancement d'une formation ou d'un ebook.",
    "result": "un calendrier qui construit la valeur perçue avant la vente."
  },
  {
    "id": 140,
    "category": "CALENDRIER ÉDITORIAL",
    "title": "Calendrier trimestriel synthétique",
    "objective": "avoir une vue d'ensemble sur 90 jours.",
    "when": "en lien avec le Plan 90 jours (Partie 15).",
    "prompt": "Propose une vue d'ensemble trimestrielle (12 semaines) de mon contenu sur [MA NICHE], avec un thème dominant par mois.",
    "variables": "[MA NICHE]",
    "example": "mois 1 fondations, mois 2 approfondissement, mois 3 monétisation.",
    "result": "une planification à moyen terme cohérente avec le Plan 90 jours."
  },
  {
    "id": 141,
    "category": "MONÉTISATION",
    "title": "Choix du modèle prioritaire",
    "objective": "identifier le modèle de monétisation le plus adapté à sa situation actuelle.",
    "when": "Partie 12, Exercice 14.",
    "prompt": "Voici ma niche [MA NICHE], mon audience actuelle [TAILLE D'AUDIENCE], et mon objectif [MON OBJECTIF]. Parmi les 9 modèles de monétisation YouTube, lesquels sont les plus réalistes à court terme ?",
    "variables": "[MA NICHE], [TAILLE D'AUDIENCE], [MON OBJECTIF]",
    "example": "chaîne débutante avec un objectif de revenu complémentaire.",
    "result": "une priorisation réaliste plutôt qu'une liste théorique de tous les modèles."
  },
  {
    "id": 142,
    "category": "MONÉTISATION",
    "title": "Construction d'un tunnel simple",
    "objective": "structurer un tunnel de conversion basique.",
    "when": "Partie 12, Exercice 15.",
    "prompt": "Construis un tunnel simple en 4 étapes (vidéo gratuite CTA ressource/offre conversion) pour le modèle [MODÈLE CHOISI], sur la niche [MA NICHE].",
    "variables": "[MODÈLE CHOISI], [MA NICHE]",
    "example": "modèle \"formation\", niche \"montage vidéo\".",
    "result": "un tunnel logique à mettre en place progressivement."
  },
  {
    "id": 143,
    "category": "MONÉTISATION",
    "title": "Idée de ressource gratuite (lead magnet)",
    "objective": "générer une idée de ressource gratuite pour la génération de prospects.",
    "when": "en lien avec le Modèle 9 (Partie 12).",
    "prompt": "Propose 5 idées de ressources gratuites (checklist, mini-guide, modèle) à forte valeur perçue pour l'audience de [MA NICHE].",
    "variables": "[MA NICHE]",
    "example": "niche \"productivité\" checklist \"routine matinale efficace\".",
    "result": "une ressource à créer pour amorcer un tunnel de génération de prospects."
  },
  {
    "id": 144,
    "category": "MONÉTISATION",
    "title": "Présentation d'une offre sans sonner commercial",
    "objective": "rédiger une présentation d'offre qui reste naturelle dans une vidéo de contenu.",
    "when": "pour éviter un ton trop promotionnel (voir erreurs fréquentes, Partie 12).",
    "prompt": "Rédige une présentation courte de mon offre [TYPE D'OFFRE] à intégrer en fin de vidéo, sans sonner commercial ni insistant.",
    "variables": "[TYPE D'OFFRE]",
    "example": "offre de coaching présentée naturellement après un contenu à valeur ajoutée.",
    "result": "une présentation d'offre alignée avec le ton pédagogique du contenu."
  },
  {
    "id": 145,
    "category": "MONÉTISATION",
    "title": "Vérification d'absence de promesse garantie",
    "objective": "s'assurer qu'aucun contenu ne promet un revenu garanti.",
    "when": "en relecture avant publication de contenu lié à la monétisation.",
    "prompt": "Relis ce texte et signale toute formulation qui pourrait laisser entendre un revenu garanti ou un résultat certain : [TEXTE].",
    "variables": "[TEXTE]",
    "example": "script ou description mentionnant des gains potentiels.",
    "result": "un texte corrigé, conforme à la règle du livre sur l'absence de promesse de revenu garanti."
  },
  {
    "id": 146,
    "category": "BUSINESS",
    "title": "Positionnement business global",
    "objective": "clarifier comment YouTube s'intègre dans une stratégie business plus large.",
    "when": "pour prendre du recul sur l'ensemble du projet.",
    "prompt": "Comment ma chaîne YouTube sur [MA NICHE] peut-elle s'intégrer dans une stratégie business plus large incluant [AUTRES ACTIVITÉS/PROJETS] ?",
    "variables": "[MA NICHE], [AUTRES ACTIVITÉS/PROJETS]",
    "example": "chaîne YouTube en complément d'une activité de e-commerce existante.",
    "result": "une vision d'ensemble plutôt qu'une chaîne isolée du reste de l'activité."
  },
  {
    "id": 147,
    "category": "BUSINESS",
    "title": "Priorisation des tâches",
    "objective": "identifier les tâches à plus fort impact pour une période donnée.",
    "when": "en cas de temps limité à consacrer au projet.",
    "prompt": "Voici toutes les tâches liées à ma chaîne YouTube en cours : [LISTE DE TÂCHES]. Aide-moi à identifier les 3 tâches à plus fort impact pour ce mois-ci.",
    "variables": "[LISTE DE TÂCHES]",
    "example": "liste incluant script, montage, SEO, veille concurrentielle, réponse aux commentaires.",
    "result": "une priorisation réaliste plutôt qu'une tentative de tout faire à la fois."
  },
  {
    "id": 148,
    "category": "BUSINESS",
    "title": "Diversification des revenus",
    "objective": "anticiper une stratégie de diversification progressive des modèles de monétisation.",
    "when": "une fois un premier modèle de monétisation stabilisé.",
    "prompt": "Mon modèle de monétisation actuel est [MODÈLE ACTUEL], stable depuis [DURÉE]. Quel serait un second modèle cohérent à ajouter progressivement ?",
    "variables": "[MODÈLE ACTUEL], [DURÉE]",
    "example": "affiliation stabilisée, envisager d'ajouter un produit digital propre.",
    "result": "une diversification progressive plutôt qu'un changement brutal de stratégie."
  },
  {
    "id": 149,
    "category": "BUSINESS",
    "title": "Bilan semestriel du projet",
    "objective": "faire un point d'ensemble sur la progression du projet YouTube-business.",
    "when": "tous les 6 mois environ.",
    "prompt": "Voici un résumé de ma progression depuis le lancement : [RÉSUMÉ DE PROGRESSION]. Aide-moi à identifier ce qui a le mieux fonctionné et ce qui mérite d'être ajusté pour les 6 prochains mois.",
    "variables": "[RÉSUMÉ DE PROGRESSION]",
    "example": "évolution de l'audience, des revenus, et de la régularité sur 6 mois.",
    "result": "un bilan structuré pour ajuster la stratégie à moyen terme."
  },
  {
    "id": 150,
    "category": "BUSINESS",
    "title": "Vision à long terme",
    "objective": "clarifier où l'on souhaite amener le projet sur le long terme.",
    "when": "en fin de parcours avec ce livre, pour se projeter au-delà des plans à 90 jours.",
    "prompt": "En me basant sur ma progression actuelle sur [MA NICHE], aide-moi à formuler une vision réaliste de ce que pourrait devenir ce projet dans 2 ans.",
    "variables": "[MA NICHE]",
    "example": "passage d'un revenu complémentaire à une activité principale, ou consolidation en tant que canal secondaire.",
    "result": "une direction à long terme, sans promesse de résultat garanti, qui guide les décisions des prochains mois."
  }
];
